### ISSUE TITLE
Speaker Onclick

### ISSUE THREAD

**Issue by hbecker1** [bjornmeansbear/daretoknow#5]
On the speaker page, right now it is a hover effect to show their bio, it needs to be an onclick so that I can include their linked in account as well.

**Comment by bjornmeansbear** [comment]
we probably need to rework that whole page then...

**Comment by bjornmeansbear** [comment]
does clicking one close any other open one?
like: http://contemporary.ookb.co/about/

or do they stay open until you click them again?

**Comment by bjornmeansbear** [comment]
resolved w/ d481cff6cd284a3f637d69c0a36cb7505d391b39

need to fix styling of titles now since I changed the HTML around a bit, but the functionality is there
